import { z } from 'zod';
import {
  authHeaderSchema,
  errorEnvelopeSchema,
  provisioningGenerateIsoPayloadResponseSchema,
  provisioningGenerateIsoPayloadSchema,
  provisioningProgressPathSchema,
  provisioningProgressResponseSchema,
  provisioningReportProgressResponseSchema,
  provisioningReportProgressSchema,
  provisioningValidateTokenResponseSchema,
  provisioningValidateTokenSchema,
  successEnvelopeSchema,
  unattendProfileCreateSchema,
  unattendProfileDeleteResponseSchema,
  unattendProfilePathSchema,
  unattendProfileRecordSchema,
  unattendProfileUpdateSchema,
} from './schemas.js';

export const contractRoutesProvisioning = {
  provisioningGenerateIsoPayload: {
    method: 'POST',
    path: '/api/v1/provisioning/generate-iso-payload',
    headers: authHeaderSchema,
    body: provisioningGenerateIsoPayloadSchema,
    responses: {
      200: successEnvelopeSchema(provisioningGenerateIsoPayloadResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Generate unattend ISO payload files',
  },
  provisioningGetProgress: {
    method: 'GET',
    path: '/api/v1/provisioning/progress/:vmUuid',
    headers: authHeaderSchema,
    pathParams: provisioningProgressPathSchema,
    responses: {
      200: successEnvelopeSchema(provisioningProgressResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Get provisioning progress by VM UUID',
  },
  provisioningReportProgress: {
    method: 'POST',
    path: '/api/v1/provisioning/report-progress',
    body: provisioningReportProgressSchema,
    responses: {
      200: successEnvelopeSchema(provisioningReportProgressResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
    },
    summary: 'Report provisioning step progress from VM bootstrap',
  },
  provisioningValidateToken: {
    method: 'POST',
    path: '/api/v1/provisioning/validate-token',
    body: provisioningValidateTokenSchema,
    responses: {
      200: successEnvelopeSchema(provisioningValidateTokenResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
    },
    summary: 'Validate provisioning token for VM bootstrap',
  },
  unattendProfilesCreate: {
    method: 'POST',
    path: '/api/v1/unattend-profiles',
    headers: authHeaderSchema,
    body: unattendProfileCreateSchema,
    responses: {
      201: successEnvelopeSchema(unattendProfileRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
    },
    summary: 'Create unattend profile',
  },
  unattendProfilesDelete: {
    method: 'DELETE',
    path: '/api/v1/unattend-profiles/:id',
    headers: authHeaderSchema,
    pathParams: unattendProfilePathSchema,
    responses: {
      200: successEnvelopeSchema(unattendProfileDeleteResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete unattend profile',
  },
  unattendProfilesList: {
    method: 'GET',
    path: '/api/v1/unattend-profiles',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.array(unattendProfileRecordSchema)),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List unattend profiles',
  },
  unattendProfilesUpdate: {
    method: 'PUT',
    path: '/api/v1/unattend-profiles/:id',
    headers: authHeaderSchema,
    pathParams: unattendProfilePathSchema,
    body: unattendProfileUpdateSchema,
    responses: {
      200: successEnvelopeSchema(unattendProfileRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
    },
    summary: 'Update unattend profile',
  },
} as const;
