import { z } from 'zod';
import {
  authHeaderSchema,
  errorEnvelopeSchema,
  settingsApiKeysMutationSchema,
  settingsApiKeysSchema,
  settingsNotificationEventsMutationSchema,
  settingsNotificationEventsSchema,
  settingsProxyMutationSchema,
  settingsProxySchema,
  successEnvelopeSchema,
  themeAssetCompleteSchema,
  themeAssetDeleteResultSchema,
  themeAssetPresignUploadResponseSchema,
  themeAssetPresignUploadSchema,
  themeAssetSchema,
  themeAssetsListSchema,
} from './schemas.js';

export const contractRoutesSettingsTheme = {
  settingsApiKeysGet: {
    method: 'GET',
    path: '/api/v1/settings/api_keys',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.union([settingsApiKeysSchema, z.null()])),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get API keys settings',
  },
  settingsApiKeysPut: {
    method: 'PUT',
    path: '/api/v1/settings/api_keys',
    headers: authHeaderSchema,
    body: settingsApiKeysMutationSchema,
    responses: {
      200: successEnvelopeSchema(settingsApiKeysSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Update API keys settings',
  },
  settingsNotificationEventsGet: {
    method: 'GET',
    path: '/api/v1/settings/notifications/events',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.union([settingsNotificationEventsSchema, z.null()])),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get notification events settings',
  },
  settingsNotificationEventsPut: {
    method: 'PUT',
    path: '/api/v1/settings/notifications/events',
    headers: authHeaderSchema,
    body: settingsNotificationEventsMutationSchema,
    responses: {
      200: successEnvelopeSchema(settingsNotificationEventsSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Update notification events settings',
  },
  settingsProxyGet: {
    method: 'GET',
    path: '/api/v1/settings/proxy',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.union([settingsProxySchema, z.null()])),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get proxy settings',
  },
  settingsProxyPut: {
    method: 'PUT',
    path: '/api/v1/settings/proxy',
    headers: authHeaderSchema,
    body: settingsProxyMutationSchema,
    responses: {
      200: successEnvelopeSchema(settingsProxySchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Update proxy settings',
  },
  themeAssetsComplete: {
    method: 'POST',
    path: '/api/v1/theme-assets/complete',
    headers: authHeaderSchema,
    body: themeAssetCompleteSchema,
    responses: {
      200: successEnvelopeSchema(themeAssetSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Mark uploaded theme asset as ready',
  },
  themeAssetsDelete: {
    method: 'DELETE',
    path: '/api/v1/theme-assets/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(themeAssetDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Delete theme asset',
  },
  themeAssetsList: {
    method: 'GET',
    path: '/api/v1/theme-assets',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(themeAssetsListSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'List uploaded theme background assets',
  },
  themeAssetsPresignUpload: {
    method: 'POST',
    path: '/api/v1/theme-assets/presign-upload',
    headers: authHeaderSchema,
    body: themeAssetPresignUploadSchema,
    responses: {
      201: successEnvelopeSchema(themeAssetPresignUploadResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Create pre-signed upload URL for theme asset',
  },
} as const;
