import { z } from 'zod';
import {
  authHeaderSchema,
  errorEnvelopeSchema,
  infraConnectionStatusSchema,
  infraDeleteVmQuerySchema,
  infraNodePathSchema,
  infraNodeVmidPathSchema,
  infraSendKeyBodySchema,
  infraTaskStatusPathSchema,
  infraUpidResponseSchema,
  infraVmActionPathSchema,
  infraVmConfigUpdateSchema,
  successEnvelopeSchema,
} from './schemas.js';

export const contractRoutesInfraProxmox = {
  infraClusterResources: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/cluster/resources',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.array(z.record(z.unknown()))),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Get Proxmox cluster resources',
  },
  infraDeleteVm: {
    method: 'DELETE',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    query: infraDeleteVmQuerySchema,
    responses: {
      200: successEnvelopeSchema(infraUpidResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Delete VM on Proxmox node',
  },
  infraGetTaskStatus: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/tasks/:upid/status',
    headers: authHeaderSchema,
    pathParams: infraTaskStatusPathSchema,
    responses: {
      200: successEnvelopeSchema(z.record(z.unknown())),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Get Proxmox task status by UPID',
  },
  infraGetVmConfig: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/config',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    responses: {
      200: successEnvelopeSchema(z.record(z.unknown())),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Read VM config from Proxmox API',
  },
  infraGetVmCurrentStatus: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/status/current',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    responses: {
      200: successEnvelopeSchema(z.record(z.unknown())),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Read current VM runtime status',
  },
  infraListNodeVms: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu',
    headers: authHeaderSchema,
    pathParams: infraNodePathSchema,
    responses: {
      200: successEnvelopeSchema(z.array(z.record(z.unknown()))),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'List QEMU VMs for node',
  },
  infraProxmoxStatus: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/status',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(infraConnectionStatusSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Get Proxmox connectivity status',
  },
  infraSendKey: {
    method: 'POST',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/sendkey',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    body: infraSendKeyBodySchema,
    responses: {
      200: successEnvelopeSchema(
        z.object({
          transport: z.string().trim().min(1).optional(),
          upid: z.union([z.string().trim(), z.null()]),
        }),
      ),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Send key to VM console',
  },
  infraUpdateVmConfig: {
    method: 'PUT',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/config',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    body: infraVmConfigUpdateSchema,
    responses: {
      200: successEnvelopeSchema(infraUpidResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Update VM config through Proxmox API',
  },
  infraVmAction: {
    method: 'POST',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/status/:action',
    headers: authHeaderSchema,
    pathParams: infraVmActionPathSchema,
    body: z.object({}).passthrough().optional(),
    responses: {
      200: successEnvelopeSchema(infraUpidResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Execute VM lifecycle action',
  },
} as const;
