import {
  authHeaderSchema,
  errorEnvelopeSchema,
  licenseHeartbeatResponseSchema,
  licenseHeartbeatSchema,
  licenseLeaseRequestSchema,
  licenseLeaseResponseSchema,
  licenseRevokeResponseSchema,
  licenseRevokeSchema,
  successEnvelopeSchema,
} from './schemas.js';

export const contractRoutesLicense = {
  licenseHeartbeat: {
    method: 'POST',
    path: '/api/v1/license/heartbeat',
    headers: authHeaderSchema,
    body: licenseHeartbeatSchema,
    responses: {
      200: successEnvelopeSchema(licenseHeartbeatResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Heartbeat existing execution lease',
  },
  licenseLease: {
    method: 'POST',
    path: '/api/v1/license/lease',
    headers: authHeaderSchema,
    body: licenseLeaseRequestSchema,
    responses: {
      201: successEnvelopeSchema(licenseLeaseResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Issue execution lease token',
  },
  licenseRevoke: {
    method: 'POST',
    path: '/api/v1/license/revoke',
    headers: authHeaderSchema,
    body: licenseRevokeSchema,
    responses: {
      200: successEnvelopeSchema(licenseRevokeResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Revoke execution lease',
  },
} as const;
