import { z } from 'zod';
import {
  authHeaderSchema,
  errorEnvelopeSchema,
  successEnvelopeSchema,
  workspaceCalendarMutationSchema,
  workspaceCalendarRecordSchema,
  workspaceDeleteResultSchema,
  workspaceKanbanMutationSchema,
  workspaceKanbanRecordSchema,
  workspaceListQuerySchema,
  workspaceNotesMutationSchema,
  workspaceNotesRecordSchema,
} from './schemas.js';

export const contractRoutesWorkspace = {
  workspaceCalendarCreate: {
    method: 'POST',
    path: '/api/v1/workspace/calendar',
    headers: authHeaderSchema,
    body: workspaceCalendarMutationSchema,
    responses: {
      201: successEnvelopeSchema(workspaceCalendarRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create workspace calendar event',
  },
  workspaceCalendarDelete: {
    method: 'DELETE',
    path: '/api/v1/workspace/calendar/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete workspace calendar event',
  },
  workspaceCalendarGet: {
    method: 'GET',
    path: '/api/v1/workspace/calendar/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceCalendarRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get workspace calendar event by id',
  },
  workspaceCalendarList: {
    method: 'GET',
    path: '/api/v1/workspace/calendar',
    headers: authHeaderSchema,
    query: workspaceListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(workspaceCalendarRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List workspace calendar events',
  },
  workspaceCalendarPatch: {
    method: 'PATCH',
    path: '/api/v1/workspace/calendar/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: workspaceCalendarMutationSchema,
    responses: {
      200: successEnvelopeSchema(workspaceCalendarRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch workspace calendar event',
  },
  workspaceNotesCreate: {
    method: 'POST',
    path: '/api/v1/workspace/notes',
    headers: authHeaderSchema,
    body: workspaceNotesMutationSchema,
    responses: {
      201: successEnvelopeSchema(workspaceNotesRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create workspace note',
  },
  workspaceNotesDelete: {
    method: 'DELETE',
    path: '/api/v1/workspace/notes/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete workspace note',
  },
  workspaceNotesGet: {
    method: 'GET',
    path: '/api/v1/workspace/notes/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceNotesRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get workspace note by id',
  },
  workspaceNotesList: {
    method: 'GET',
    path: '/api/v1/workspace/notes',
    headers: authHeaderSchema,
    query: workspaceListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(workspaceNotesRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List workspace notes',
  },
  workspaceNotesPatch: {
    method: 'PATCH',
    path: '/api/v1/workspace/notes/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: workspaceNotesMutationSchema,
    responses: {
      200: successEnvelopeSchema(workspaceNotesRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch workspace note',
  },
  workspaceKanbanCreate: {
    method: 'POST',
    path: '/api/v1/workspace/kanban',
    headers: authHeaderSchema,
    body: workspaceKanbanMutationSchema,
    responses: {
      201: successEnvelopeSchema(workspaceKanbanRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create workspace kanban task',
  },
  workspaceKanbanDelete: {
    method: 'DELETE',
    path: '/api/v1/workspace/kanban/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete workspace kanban task',
  },
  workspaceKanbanGet: {
    method: 'GET',
    path: '/api/v1/workspace/kanban/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceKanbanRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get workspace kanban task by id',
  },
  workspaceKanbanList: {
    method: 'GET',
    path: '/api/v1/workspace/kanban',
    headers: authHeaderSchema,
    query: workspaceListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(workspaceKanbanRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List workspace kanban tasks',
  },
  workspaceKanbanPatch: {
    method: 'PATCH',
    path: '/api/v1/workspace/kanban/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: workspaceKanbanMutationSchema,
    responses: {
      200: successEnvelopeSchema(workspaceKanbanRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch workspace kanban task',
  },
} as const;
