import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import {
  agentHeartbeatSchema,
  agentListQuerySchema,
  agentPairingCreateSchema,
  agentPairingRecordSchema,
  agentRecordSchema,
  artifactAssignmentPathSchema,
  artifactAssignmentQuerySchema,
  artifactAssignmentRecordSchema,
  artifactAssignSchema,
  artifactDownloadResolutionSchema,
  artifactEffectiveAssignmentSchema,
  artifactReleaseCreateSchema,
  artifactReleaseRecordSchema,
  artifactResolveDownloadSchema,
  authHeaderSchema,
  authVerifyResponseSchema,
  authWhoAmIResponseSchema,
  botBanDetailsSchema,
  botDeleteResultSchema,
  botLifecycleIsBannedSchema,
  botLifecycleSchema,
  botLifecycleTransitionItemSchema,
  botLifecycleTransitionSchema,
  botListQuerySchema,
  botMutationSchema,
  botRecordSchema,
  clientLogsIngestResultSchema,
  clientLogsIngestSchema,
  diagnosticsTraceResponseSchema,
  errorEnvelopeSchema,
  financeDailyStatsSchema,
  financeDeleteResultSchema,
  financeGoldPriceHistorySchema,
  financeListQuerySchema,
  financeOperationCreateSchema,
  financeOperationPatchSchema,
  financeOperationRecordSchema,
  healthLiveSchema,
  healthReadySchema,
  healthSummarySchema,
  infraCloneRequestSchema,
  infraConnectionStatusSchema,
  infraDeleteVmQuerySchema,
  infraNodePathSchema,
  infraNodeVmidPathSchema,
  infraSendKeyBodySchema,
  infraSshExecResultSchema,
  infraSshExecSchema,
  infraSshVmConfigPathSchema,
  infraTaskStatusPathSchema,
  infraUpidResponseSchema,
  infraVmActionPathSchema,
  infraVmConfigReadResultSchema,
  infraVmConfigUpdateSchema,
  infraVmConfigWriteResultSchema,
  infraVmConfigWriteSchema,
  ipqsBatchResponseSchema,
  ipqsCheckBatchBodySchema,
  ipqsCheckBodySchema,
  ipqsCheckResponseSchema,
  ipqsStatusSchema,
  licenseHeartbeatResponseSchema,
  licenseHeartbeatSchema,
  licenseLeaseRequestSchema,
  licenseLeaseResponseSchema,
  licenseRevokeResponseSchema,
  licenseRevokeSchema,
  playbookCreateSchema,
  playbookDeleteResultSchema,
  playbookRecordSchema,
  playbookUpdateSchema,
  playbookValidateBodySchema,
  playbookValidationResultSchema,
  provisioningGenerateIsoPayloadResponseSchema,
  provisioningGenerateIsoPayloadSchema,
  provisioningProgressPathSchema,
  provisioningProgressResponseSchema,
  provisioningReportProgressResponseSchema,
  provisioningReportProgressSchema,
  provisioningValidateTokenResponseSchema,
  provisioningValidateTokenSchema,
  resourceDeleteResultSchema,
  resourceKindSchema,
  resourceListQuerySchema,
  resourceMutationSchema,
  resourceRecordSchema,
  secretBindingCreateSchema,
  secretBindingRecordSchema,
  secretBindingsListQuerySchema,
  secretCreateSchema,
  secretMetaRecordSchema,
  secretRotateSchema,
  settingsApiKeysMutationSchema,
  settingsApiKeysSchema,
  settingsNotificationEventsMutationSchema,
  settingsNotificationEventsSchema,
  settingsProxyMutationSchema,
  settingsProxySchema,
  successEnvelopeSchema,
  themeAssetCompleteSchema,
  themeAssetDeleteResultSchema,
  themeAssetPresignUploadResponseSchema,
  themeAssetPresignUploadSchema,
  themeAssetSchema,
  themeAssetsListSchema,
  unattendProfileCreateSchema,
  unattendProfileDeleteResponseSchema,
  unattendProfilePathSchema,
  unattendProfileRecordSchema,
  unattendProfileUpdateSchema,
  vmOpsActionSchema,
  vmOpsCommandCreateSchema,
  vmOpsCommandListQuerySchema,
  vmOpsCommandNextQuerySchema,
  vmOpsCommandSchema,
  vmOpsCommandUpdateSchema,
  vmOpsDispatchBodySchema,
  vmRecordSchema,
  vmRegisterSchema,
  vmResolvePathSchema,
  workspaceCalendarMutationSchema,
  workspaceCalendarRecordSchema,
  workspaceDeleteResultSchema,
  workspaceKanbanMutationSchema,
  workspaceKanbanRecordSchema,
  workspaceListQuerySchema,
  workspaceNotesMutationSchema,
  workspaceNotesRecordSchema,
  wowNamesQuerySchema,
  wowNamesResponseSchema,
} from './schemas.js';

const c = initContract();

export const apiContract = c.router({
  healthSummary: {
    method: 'GET',
    path: '/api/v1/health',
    responses: {
      200: successEnvelopeSchema(healthSummarySchema),
    },
    summary: 'Get API health summary',
  },
  healthLive: {
    method: 'GET',
    path: '/api/v1/health/live',
    responses: {
      200: successEnvelopeSchema(healthLiveSchema),
    },
    summary: 'Get liveness check',
  },
  healthReady: {
    method: 'GET',
    path: '/api/v1/health/ready',
    responses: {
      200: successEnvelopeSchema(healthReadySchema),
      503: successEnvelopeSchema(healthReadySchema),
    },
    summary: 'Get readiness check',
  },
  diagnosticsTrace: {
    method: 'GET',
    path: '/api/v1/diag/trace',
    responses: {
      200: successEnvelopeSchema(diagnosticsTraceResponseSchema),
      404: errorEnvelopeSchema,
    },
    summary: 'Get diagnostic trace context snapshot',
  },
  clientLogsIngest: {
    method: 'POST',
    path: '/api/v1/client-logs',
    body: clientLogsIngestSchema,
    responses: {
      200: successEnvelopeSchema(clientLogsIngestResultSchema),
      400: errorEnvelopeSchema,
      429: errorEnvelopeSchema,
    },
    summary: 'Ingest frontend structured logs',
  },
  authVerify: {
    method: 'GET',
    path: '/api/v1/auth/verify',
    headers: authHeaderSchema,
    responses: {
      200: authVerifyResponseSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Verify auth token',
  },
  authWhoAmI: {
    method: 'GET',
    path: '/api/v1/auth/whoami',
    headers: authHeaderSchema,
    responses: {
      200: authWhoAmIResponseSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Return current identity',
  },
  licenseLease: {
    method: 'POST',
    path: '/api/v1/license/lease',
    headers: authHeaderSchema,
    body: licenseLeaseRequestSchema,
    responses: {
      201: successEnvelopeSchema(licenseLeaseResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Issue execution lease token',
  },
  licenseHeartbeat: {
    method: 'POST',
    path: '/api/v1/license/heartbeat',
    headers: authHeaderSchema,
    body: licenseHeartbeatSchema,
    responses: {
      200: successEnvelopeSchema(licenseHeartbeatResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Heartbeat existing execution lease',
  },
  licenseRevoke: {
    method: 'POST',
    path: '/api/v1/license/revoke',
    headers: authHeaderSchema,
    body: licenseRevokeSchema,
    responses: {
      200: successEnvelopeSchema(licenseRevokeResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Revoke execution lease',
  },
  provisioningValidateToken: {
    method: 'POST',
    path: '/api/v1/provisioning/validate-token',
    body: provisioningValidateTokenSchema,
    responses: {
      200: successEnvelopeSchema(provisioningValidateTokenResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
    },
    summary: 'Validate provisioning token for VM bootstrap',
  },
  provisioningReportProgress: {
    method: 'POST',
    path: '/api/v1/provisioning/report-progress',
    body: provisioningReportProgressSchema,
    responses: {
      200: successEnvelopeSchema(provisioningReportProgressResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
    },
    summary: 'Report provisioning step progress from VM bootstrap',
  },
  provisioningGetProgress: {
    method: 'GET',
    path: '/api/v1/provisioning/progress/:vmUuid',
    headers: authHeaderSchema,
    pathParams: provisioningProgressPathSchema,
    responses: {
      200: successEnvelopeSchema(provisioningProgressResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Get provisioning progress by VM UUID',
  },
  unattendProfilesList: {
    method: 'GET',
    path: '/api/v1/unattend-profiles',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.array(unattendProfileRecordSchema)),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List unattend profiles',
  },
  unattendProfilesCreate: {
    method: 'POST',
    path: '/api/v1/unattend-profiles',
    headers: authHeaderSchema,
    body: unattendProfileCreateSchema,
    responses: {
      201: successEnvelopeSchema(unattendProfileRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
    },
    summary: 'Create unattend profile',
  },
  unattendProfilesUpdate: {
    method: 'PUT',
    path: '/api/v1/unattend-profiles/:id',
    headers: authHeaderSchema,
    pathParams: unattendProfilePathSchema,
    body: unattendProfileUpdateSchema,
    responses: {
      200: successEnvelopeSchema(unattendProfileRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
    },
    summary: 'Update unattend profile',
  },
  unattendProfilesDelete: {
    method: 'DELETE',
    path: '/api/v1/unattend-profiles/:id',
    headers: authHeaderSchema,
    pathParams: unattendProfilePathSchema,
    responses: {
      200: successEnvelopeSchema(unattendProfileDeleteResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete unattend profile',
  },
  provisioningGenerateIsoPayload: {
    method: 'POST',
    path: '/api/v1/provisioning/generate-iso-payload',
    headers: authHeaderSchema,
    body: provisioningGenerateIsoPayloadSchema,
    responses: {
      200: successEnvelopeSchema(provisioningGenerateIsoPayloadResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Generate unattend ISO payload files',
  },
  botsList: {
    method: 'GET',
    path: '/api/v1/bots',
    headers: authHeaderSchema,
    query: botListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(botRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List bots',
  },
  botsGet: {
    method: 'GET',
    path: '/api/v1/bots/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(botRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get bot by id',
  },
  botsCreate: {
    method: 'POST',
    path: '/api/v1/bots',
    headers: authHeaderSchema,
    body: botMutationSchema,
    responses: {
      201: successEnvelopeSchema(botRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create bot',
  },
  botsPatch: {
    method: 'PATCH',
    path: '/api/v1/bots/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: botMutationSchema,
    responses: {
      200: successEnvelopeSchema(botRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch bot',
  },
  botsDelete: {
    method: 'DELETE',
    path: '/api/v1/bots/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(botDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete bot',
  },
  botsLifecycleGet: {
    method: 'GET',
    path: '/api/v1/bots/:id/lifecycle',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(z.union([botLifecycleSchema, z.null()])),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get bot lifecycle state',
  },
  botsLifecycleTransitions: {
    method: 'GET',
    path: '/api/v1/bots/:id/lifecycle/transitions',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(z.array(botLifecycleTransitionItemSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get bot lifecycle transitions',
  },
  botsLifecycleIsBanned: {
    method: 'GET',
    path: '/api/v1/bots/:id/lifecycle/is-banned',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(botLifecycleIsBannedSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Check whether bot is banned',
  },
  botsLifecycleTransition: {
    method: 'POST',
    path: '/api/v1/bots/:id/lifecycle/transition',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: botLifecycleTransitionSchema,
    responses: {
      200: successEnvelopeSchema(botRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Transition bot lifecycle status',
  },
  botsLifecycleBan: {
    method: 'POST',
    path: '/api/v1/bots/:id/lifecycle/ban',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: botBanDetailsSchema,
    responses: {
      200: successEnvelopeSchema(botRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Ban bot via lifecycle endpoint',
  },
  botsLifecycleUnban: {
    method: 'POST',
    path: '/api/v1/bots/:id/lifecycle/unban',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: z.object({}).passthrough().optional(),
    responses: {
      200: successEnvelopeSchema(botRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Unban bot via lifecycle endpoint',
  },
  resourcesList: {
    method: 'GET',
    path: '/api/v1/resources/:kind',
    headers: authHeaderSchema,
    pathParams: z.object({
      kind: resourceKindSchema,
    }),
    query: resourceListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(resourceRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List resource entities by kind',
  },
  resourcesGet: {
    method: 'GET',
    path: '/api/v1/resources/:kind/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      kind: resourceKindSchema,
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(resourceRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get resource entity by id',
  },
  resourcesCreate: {
    method: 'POST',
    path: '/api/v1/resources/:kind',
    headers: authHeaderSchema,
    pathParams: z.object({
      kind: resourceKindSchema,
    }),
    body: resourceMutationSchema,
    responses: {
      201: successEnvelopeSchema(resourceRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create resource entity',
  },
  resourcesUpdate: {
    method: 'PATCH',
    path: '/api/v1/resources/:kind/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      kind: resourceKindSchema,
      id: z.string().min(1),
    }),
    body: resourceMutationSchema,
    responses: {
      200: successEnvelopeSchema(resourceRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Update resource entity',
  },
  resourcesDelete: {
    method: 'DELETE',
    path: '/api/v1/resources/:kind/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      kind: resourceKindSchema,
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(resourceDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete resource entity',
  },
  resourcesUpsert: {
    method: 'PATCH',
    path: '/api/v1/resources/:kind/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      kind: resourceKindSchema,
      id: z.string().min(1),
    }),
    body: resourceMutationSchema,
    responses: {
      200: successEnvelopeSchema(resourceRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Deprecated alias for update resource entity',
  },
  settingsApiKeysGet: {
    method: 'GET',
    path: '/api/v1/settings/api_keys',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.union([settingsApiKeysSchema, z.null()])),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get API keys settings',
  },
  settingsApiKeysPut: {
    method: 'PUT',
    path: '/api/v1/settings/api_keys',
    headers: authHeaderSchema,
    body: settingsApiKeysMutationSchema,
    responses: {
      200: successEnvelopeSchema(settingsApiKeysSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Update API keys settings',
  },
  settingsProxyGet: {
    method: 'GET',
    path: '/api/v1/settings/proxy',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.union([settingsProxySchema, z.null()])),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get proxy settings',
  },
  settingsProxyPut: {
    method: 'PUT',
    path: '/api/v1/settings/proxy',
    headers: authHeaderSchema,
    body: settingsProxyMutationSchema,
    responses: {
      200: successEnvelopeSchema(settingsProxySchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Update proxy settings',
  },
  settingsNotificationEventsGet: {
    method: 'GET',
    path: '/api/v1/settings/notifications/events',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.union([settingsNotificationEventsSchema, z.null()])),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get notification events settings',
  },
  settingsNotificationEventsPut: {
    method: 'PUT',
    path: '/api/v1/settings/notifications/events',
    headers: authHeaderSchema,
    body: settingsNotificationEventsMutationSchema,
    responses: {
      200: successEnvelopeSchema(settingsNotificationEventsSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Update notification events settings',
  },
  themeAssetsList: {
    method: 'GET',
    path: '/api/v1/theme-assets',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(themeAssetsListSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'List uploaded theme background assets',
  },
  themeAssetsPresignUpload: {
    method: 'POST',
    path: '/api/v1/theme-assets/presign-upload',
    headers: authHeaderSchema,
    body: themeAssetPresignUploadSchema,
    responses: {
      201: successEnvelopeSchema(themeAssetPresignUploadResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Create pre-signed upload URL for theme asset',
  },
  themeAssetsComplete: {
    method: 'POST',
    path: '/api/v1/theme-assets/complete',
    headers: authHeaderSchema,
    body: themeAssetCompleteSchema,
    responses: {
      200: successEnvelopeSchema(themeAssetSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Mark uploaded theme asset as ready',
  },
  themeAssetsDelete: {
    method: 'DELETE',
    path: '/api/v1/theme-assets/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(themeAssetDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Delete theme asset',
  },
  workspaceNotesList: {
    method: 'GET',
    path: '/api/v1/workspace/notes',
    headers: authHeaderSchema,
    query: workspaceListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(workspaceNotesRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List workspace notes',
  },
  workspaceNotesGet: {
    method: 'GET',
    path: '/api/v1/workspace/notes/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceNotesRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get workspace note by id',
  },
  workspaceNotesCreate: {
    method: 'POST',
    path: '/api/v1/workspace/notes',
    headers: authHeaderSchema,
    body: workspaceNotesMutationSchema,
    responses: {
      201: successEnvelopeSchema(workspaceNotesRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create workspace note',
  },
  workspaceNotesPatch: {
    method: 'PATCH',
    path: '/api/v1/workspace/notes/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: workspaceNotesMutationSchema,
    responses: {
      200: successEnvelopeSchema(workspaceNotesRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch workspace note',
  },
  workspaceNotesDelete: {
    method: 'DELETE',
    path: '/api/v1/workspace/notes/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete workspace note',
  },
  workspaceCalendarList: {
    method: 'GET',
    path: '/api/v1/workspace/calendar',
    headers: authHeaderSchema,
    query: workspaceListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(workspaceCalendarRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List workspace calendar events',
  },
  workspaceCalendarGet: {
    method: 'GET',
    path: '/api/v1/workspace/calendar/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceCalendarRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get workspace calendar event by id',
  },
  workspaceCalendarCreate: {
    method: 'POST',
    path: '/api/v1/workspace/calendar',
    headers: authHeaderSchema,
    body: workspaceCalendarMutationSchema,
    responses: {
      201: successEnvelopeSchema(workspaceCalendarRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create workspace calendar event',
  },
  workspaceCalendarPatch: {
    method: 'PATCH',
    path: '/api/v1/workspace/calendar/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: workspaceCalendarMutationSchema,
    responses: {
      200: successEnvelopeSchema(workspaceCalendarRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch workspace calendar event',
  },
  workspaceCalendarDelete: {
    method: 'DELETE',
    path: '/api/v1/workspace/calendar/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete workspace calendar event',
  },
  workspaceKanbanList: {
    method: 'GET',
    path: '/api/v1/workspace/kanban',
    headers: authHeaderSchema,
    query: workspaceListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(workspaceKanbanRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List workspace kanban tasks',
  },
  workspaceKanbanGet: {
    method: 'GET',
    path: '/api/v1/workspace/kanban/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceKanbanRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get workspace kanban task by id',
  },
  workspaceKanbanCreate: {
    method: 'POST',
    path: '/api/v1/workspace/kanban',
    headers: authHeaderSchema,
    body: workspaceKanbanMutationSchema,
    responses: {
      201: successEnvelopeSchema(workspaceKanbanRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create workspace kanban task',
  },
  workspaceKanbanPatch: {
    method: 'PATCH',
    path: '/api/v1/workspace/kanban/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: workspaceKanbanMutationSchema,
    responses: {
      200: successEnvelopeSchema(workspaceKanbanRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch workspace kanban task',
  },
  workspaceKanbanDelete: {
    method: 'DELETE',
    path: '/api/v1/workspace/kanban/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(workspaceDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete workspace kanban task',
  },
  financeOperationsList: {
    method: 'GET',
    path: '/api/v1/finance/operations',
    headers: authHeaderSchema,
    query: financeListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(financeOperationRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List finance operations',
  },
  financeOperationsGet: {
    method: 'GET',
    path: '/api/v1/finance/operations/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(financeOperationRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get finance operation by id',
  },
  financeOperationsCreate: {
    method: 'POST',
    path: '/api/v1/finance/operations',
    headers: authHeaderSchema,
    body: financeOperationCreateSchema,
    responses: {
      201: successEnvelopeSchema(financeOperationRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create finance operation',
  },
  financeOperationsPatch: {
    method: 'PATCH',
    path: '/api/v1/finance/operations/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: financeOperationPatchSchema,
    responses: {
      200: successEnvelopeSchema(financeOperationRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Patch finance operation',
  },
  financeOperationsDelete: {
    method: 'DELETE',
    path: '/api/v1/finance/operations/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(financeDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete finance operation',
  },
  financeDailyStats: {
    method: 'GET',
    path: '/api/v1/finance/daily-stats',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(financeDailyStatsSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Get finance daily stats',
  },
  financeGoldPriceHistory: {
    method: 'GET',
    path: '/api/v1/finance/gold-price-history',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(financeGoldPriceHistorySchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Get finance gold price history',
  },
  playbooksList: {
    method: 'GET',
    path: '/api/v1/playbooks',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.array(playbookRecordSchema)),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List playbooks',
  },
  playbooksGet: {
    method: 'GET',
    path: '/api/v1/playbooks/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(playbookRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get playbook by id',
  },
  playbooksCreate: {
    method: 'POST',
    path: '/api/v1/playbooks',
    headers: authHeaderSchema,
    body: playbookCreateSchema,
    responses: {
      201: successEnvelopeSchema(playbookRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      422: errorEnvelopeSchema,
    },
    summary: 'Create playbook',
  },
  playbooksUpdate: {
    method: 'PUT',
    path: '/api/v1/playbooks/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: playbookUpdateSchema,
    responses: {
      200: successEnvelopeSchema(playbookRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      422: errorEnvelopeSchema,
    },
    summary: 'Update playbook',
  },
  playbooksDelete: {
    method: 'DELETE',
    path: '/api/v1/playbooks/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(playbookDeleteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Delete playbook',
  },
  playbooksValidate: {
    method: 'POST',
    path: '/api/v1/playbooks/validate',
    headers: authHeaderSchema,
    body: playbookValidateBodySchema,
    responses: {
      200: successEnvelopeSchema(playbookValidationResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Validate playbook content',
  },
  ipqsStatusGet: {
    method: 'GET',
    path: '/api/v1/ipqs/status',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(ipqsStatusSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get IPQS integration status',
  },
  ipqsCheck: {
    method: 'POST',
    path: '/api/v1/ipqs/check',
    headers: authHeaderSchema,
    body: ipqsCheckBodySchema,
    responses: {
      200: successEnvelopeSchema(ipqsCheckResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Check IP quality',
  },
  ipqsCheckBatch: {
    method: 'POST',
    path: '/api/v1/ipqs/check-batch',
    headers: authHeaderSchema,
    body: ipqsCheckBatchBodySchema,
    responses: {
      200: successEnvelopeSchema(ipqsBatchResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Check IP quality in batch',
  },
  wowNamesGet: {
    method: 'GET',
    path: '/api/v1/wow-names',
    headers: authHeaderSchema,
    query: wowNamesQuerySchema,
    responses: {
      200: successEnvelopeSchema(wowNamesResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
    },
    summary: 'Get generated WoW names',
  },
  agentsList: {
    method: 'GET',
    path: '/api/v1/agents',
    headers: authHeaderSchema,
    query: agentListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(agentRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List tenant agents',
  },
  agentsCreatePairing: {
    method: 'POST',
    path: '/api/v1/agents/pairings',
    headers: authHeaderSchema,
    body: agentPairingCreateSchema,
    responses: {
      201: successEnvelopeSchema(agentPairingRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Create agent pairing code',
  },
  agentsHeartbeat: {
    method: 'POST',
    path: '/api/v1/agents/heartbeat',
    headers: authHeaderSchema,
    body: agentHeartbeatSchema,
    responses: {
      200: successEnvelopeSchema(z.record(z.unknown())),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Agent heartbeat',
  },
  vmRegister: {
    method: 'POST',
    path: '/api/v1/vm/register',
    headers: authHeaderSchema,
    body: vmRegisterSchema,
    responses: {
      201: successEnvelopeSchema(vmRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Register VM ownership binding for tenant/user scope',
  },
  vmResolve: {
    method: 'GET',
    path: '/api/v1/vm/:uuid/resolve',
    headers: authHeaderSchema,
    pathParams: vmResolvePathSchema,
    responses: {
      200: successEnvelopeSchema(vmRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Resolve VM ownership by VM UUID',
  },
  secretsCreate: {
    method: 'POST',
    path: '/api/v1/secrets',
    headers: authHeaderSchema,
    body: secretCreateSchema,
    responses: {
      201: successEnvelopeSchema(secretMetaRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Store ciphertext secret',
  },
  secretsGetMeta: {
    method: 'GET',
    path: '/api/v1/secrets/:id/meta',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().trim().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(secretMetaRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Read secret metadata without ciphertext',
  },
  secretsRotate: {
    method: 'POST',
    path: '/api/v1/secrets/:id/rotate',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().trim().min(1),
    }),
    body: secretRotateSchema,
    responses: {
      200: successEnvelopeSchema(secretMetaRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Rotate secret material',
  },
  secretsCreateBinding: {
    method: 'POST',
    path: '/api/v1/secrets/bindings',
    headers: authHeaderSchema,
    body: secretBindingCreateSchema,
    responses: {
      201: successEnvelopeSchema(secretBindingRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Create secret binding for domain scope',
  },
  secretsListBindings: {
    method: 'GET',
    path: '/api/v1/secrets/bindings',
    headers: authHeaderSchema,
    query: secretBindingsListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(secretBindingRecordSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'List secret bindings by optional scope',
  },
  artifactsCreateRelease: {
    method: 'POST',
    path: '/api/v1/artifacts/releases',
    headers: authHeaderSchema,
    body: artifactReleaseCreateSchema,
    responses: {
      201: successEnvelopeSchema(artifactReleaseRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Create artifact release',
  },
  artifactsAssign: {
    method: 'POST',
    path: '/api/v1/artifacts/assign',
    headers: authHeaderSchema,
    body: artifactAssignSchema,
    responses: {
      201: successEnvelopeSchema(artifactAssignmentRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Assign release for user or tenant default scope',
  },
  artifactsGetAssignment: {
    method: 'GET',
    path: '/api/v1/artifacts/assign/:userId/:module',
    headers: authHeaderSchema,
    pathParams: artifactAssignmentPathSchema,
    query: artifactAssignmentQuerySchema,
    responses: {
      200: successEnvelopeSchema(artifactEffectiveAssignmentSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Get effective artifact assignment for user and module',
  },
  artifactsResolveDownload: {
    method: 'POST',
    path: '/api/v1/artifacts/resolve-download',
    headers: authHeaderSchema,
    body: artifactResolveDownloadSchema,
    responses: {
      200: successEnvelopeSchema(artifactDownloadResolutionSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Resolve signed artifact download URL from lease token',
  },
  infraProxmoxLogin: {
    method: 'POST',
    path: '/api/v1/infra/proxmox/login',
    headers: authHeaderSchema,
    body: z.object({}).passthrough().optional(),
    responses: {
      200: successEnvelopeSchema(infraConnectionStatusSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Force refresh Proxmox session',
  },
  infraProxmoxStatus: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/status',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(infraConnectionStatusSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Get Proxmox connectivity status',
  },
  infraListNodeVms: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu',
    headers: authHeaderSchema,
    pathParams: infraNodePathSchema,
    responses: {
      200: successEnvelopeSchema(z.array(z.record(z.unknown()))),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'List QEMU VMs for node',
  },
  infraCloneVm: {
    method: 'POST',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/clone',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    body: infraCloneRequestSchema,
    responses: {
      200: successEnvelopeSchema(infraUpidResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Clone VM on Proxmox node',
  },
  infraGetVmConfig: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/config',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    responses: {
      200: successEnvelopeSchema(z.record(z.unknown())),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Read VM config from Proxmox API',
  },
  infraUpdateVmConfig: {
    method: 'PUT',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/config',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    body: infraVmConfigUpdateSchema,
    responses: {
      200: successEnvelopeSchema(infraUpidResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Update VM config through Proxmox API',
  },
  infraGetTaskStatus: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/tasks/:upid/status',
    headers: authHeaderSchema,
    pathParams: infraTaskStatusPathSchema,
    responses: {
      200: successEnvelopeSchema(z.record(z.unknown())),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Get Proxmox task status by UPID',
  },
  infraVmAction: {
    method: 'POST',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/status/:action',
    headers: authHeaderSchema,
    pathParams: infraVmActionPathSchema,
    body: z.object({}).passthrough().optional(),
    responses: {
      200: successEnvelopeSchema(infraUpidResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Execute VM lifecycle action',
  },
  infraDeleteVm: {
    method: 'DELETE',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    query: infraDeleteVmQuerySchema,
    responses: {
      200: successEnvelopeSchema(infraUpidResponseSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Delete VM on Proxmox node',
  },
  infraSendKey: {
    method: 'POST',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/sendkey',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    body: infraSendKeyBodySchema,
    responses: {
      200: successEnvelopeSchema(
        z.object({
          transport: z.string().trim().min(1).optional(),
          upid: z.union([z.string().trim(), z.null()]),
        }),
      ),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Send key to VM console',
  },
  infraGetVmCurrentStatus: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/nodes/:node/qemu/:vmid/status/current',
    headers: authHeaderSchema,
    pathParams: infraNodeVmidPathSchema,
    responses: {
      200: successEnvelopeSchema(z.record(z.unknown())),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Read current VM runtime status',
  },
  infraClusterResources: {
    method: 'GET',
    path: '/api/v1/infra/proxmox/cluster/resources',
    headers: authHeaderSchema,
    responses: {
      200: successEnvelopeSchema(z.array(z.record(z.unknown()))),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Get Proxmox cluster resources',
  },
  infraSshTest: {
    method: 'POST',
    path: '/api/v1/infra/ssh/test',
    headers: authHeaderSchema,
    body: z.object({}).passthrough().optional(),
    responses: {
      200: successEnvelopeSchema(infraSshExecResultSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Run SSH connection smoke test',
  },
  infraSshExec: {
    method: 'POST',
    path: '/api/v1/infra/ssh/exec',
    headers: authHeaderSchema,
    body: infraSshExecSchema,
    responses: {
      200: successEnvelopeSchema(infraSshExecResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Execute allowlisted SSH command',
  },
  infraSshReadVmConfig: {
    method: 'GET',
    path: '/api/v1/infra/ssh/vm-config/:vmid',
    headers: authHeaderSchema,
    pathParams: infraSshVmConfigPathSchema,
    responses: {
      200: successEnvelopeSchema(infraVmConfigReadResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Read raw VM config over SSH',
  },
  infraSshWriteVmConfig: {
    method: 'PUT',
    path: '/api/v1/infra/ssh/vm-config/:vmid',
    headers: authHeaderSchema,
    pathParams: infraSshVmConfigPathSchema,
    body: infraVmConfigWriteSchema,
    responses: {
      200: successEnvelopeSchema(infraVmConfigWriteResultSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
    },
    summary: 'Write raw VM config over SSH',
  },
  vmOpsCommandCreate: {
    method: 'POST',
    path: '/api/v1/vm-ops/commands',
    headers: authHeaderSchema,
    body: vmOpsCommandCreateSchema,
    responses: {
      202: successEnvelopeSchema(vmOpsCommandSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Dispatch arbitrary VM operation command',
  },
  vmOpsCommandList: {
    method: 'GET',
    path: '/api/v1/vm-ops/commands',
    headers: authHeaderSchema,
    query: vmOpsCommandListQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.array(vmOpsCommandSchema)),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'List VM operation commands',
  },
  vmOpsDispatchProxmox: {
    method: 'POST',
    path: '/api/v1/vm-ops/proxmox/:action',
    headers: authHeaderSchema,
    pathParams: z.object({
      action: vmOpsActionSchema,
    }),
    body: vmOpsDispatchBodySchema,
    responses: {
      200: successEnvelopeSchema(vmOpsCommandSchema),
      202: successEnvelopeSchema(vmOpsCommandSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Dispatch proxmox command through agent queue',
  },
  vmOpsDispatchSyncthing: {
    method: 'POST',
    path: '/api/v1/vm-ops/syncthing/:action',
    headers: authHeaderSchema,
    pathParams: z.object({
      action: vmOpsActionSchema,
    }),
    body: vmOpsDispatchBodySchema,
    responses: {
      200: successEnvelopeSchema(vmOpsCommandSchema),
      202: successEnvelopeSchema(vmOpsCommandSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Dispatch syncthing command through agent queue',
  },
  vmOpsCommandNext: {
    method: 'GET',
    path: '/api/v1/vm-ops/commands/next',
    headers: authHeaderSchema,
    query: vmOpsCommandNextQuerySchema,
    responses: {
      200: successEnvelopeSchema(z.union([vmOpsCommandSchema, z.null()])),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
    },
    summary: 'Long-poll next queued command for agent',
  },
  vmOpsCommandById: {
    method: 'GET',
    path: '/api/v1/vm-ops/commands/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    responses: {
      200: successEnvelopeSchema(vmOpsCommandSchema),
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Get command status',
  },
  vmOpsCommandPatch: {
    method: 'PATCH',
    path: '/api/v1/vm-ops/commands/:id',
    headers: authHeaderSchema,
    pathParams: z.object({
      id: z.string().min(1),
    }),
    body: vmOpsCommandUpdateSchema,
    responses: {
      200: successEnvelopeSchema(vmOpsCommandSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
    },
    summary: 'Update command status from agent',
  },
});

export type ApiContract = typeof apiContract;
