import {
  artifactAssignmentPathSchema,
  artifactAssignmentQuerySchema,
  artifactAssignmentRecordSchema,
  artifactAssignSchema,
  artifactDownloadResolutionSchema,
  artifactEffectiveAssignmentSchema,
  artifactReleaseCreateSchema,
  artifactReleaseRecordSchema,
  artifactResolveDownloadSchema,
  authHeaderSchema,
  errorEnvelopeSchema,
  successEnvelopeSchema,
} from './schemas.js';

export const contractRoutesArtifacts = {
  artifactsAssign: {
    method: 'POST',
    path: '/api/v1/artifacts/assign',
    headers: authHeaderSchema,
    body: artifactAssignSchema,
    responses: {
      201: successEnvelopeSchema(artifactAssignmentRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Assign release for user or tenant default scope',
  },
  artifactsCreateRelease: {
    method: 'POST',
    path: '/api/v1/artifacts/releases',
    headers: authHeaderSchema,
    body: artifactReleaseCreateSchema,
    responses: {
      201: successEnvelopeSchema(artifactReleaseRecordSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Create artifact release',
  },
  artifactsGetAssignment: {
    method: 'GET',
    path: '/api/v1/artifacts/assign/:userId/:module',
    headers: authHeaderSchema,
    pathParams: artifactAssignmentPathSchema,
    query: artifactAssignmentQuerySchema,
    responses: {
      200: successEnvelopeSchema(artifactEffectiveAssignmentSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Get effective artifact assignment for user and module',
  },
  artifactsResolveDownload: {
    method: 'POST',
    path: '/api/v1/artifacts/resolve-download',
    headers: authHeaderSchema,
    body: artifactResolveDownloadSchema,
    responses: {
      200: successEnvelopeSchema(artifactDownloadResolutionSchema),
      400: errorEnvelopeSchema,
      401: errorEnvelopeSchema,
      403: errorEnvelopeSchema,
      404: errorEnvelopeSchema,
      409: errorEnvelopeSchema,
      500: errorEnvelopeSchema,
      502: errorEnvelopeSchema,
      503: errorEnvelopeSchema,
    },
    summary: 'Resolve signed artifact download URL from lease token',
  },
} as const;
