export interface PlatformGroup {
  boards: [string, string][];
  cpus: { string: string; part: string }[];
  ramSpeeds: number[];
  dimmCounts: number[];
}

export const PLATFORM_GROUPS: PlatformGroup[] = [
  // X99 (LGA2011-3)
  {
    boards: [
      ['ASUS', 'X99-DELUXE'],
      ['ASUS', 'X99-DELUXE II'],
      ['ASUS', 'X99-A'],
      ['ASUS', 'X99-A II'],
      ['ASUS', 'SABERTOOTH X99'],
      ['ASUS', 'X99-E WS/USB 3.1'],
      ['ASUS', 'X99-PRO/USB 3.1'],
      ['ASUS', 'ROG STRIX X99 GAMING'],
      ['ASUS', 'ROG RAMPAGE V EXTREME'],
      ['ASUS', 'ROG RAMPAGE V EDITION 10'],
      ['ASUS', 'X99-E WS'],
      ['MSI', 'X99A GAMING PRO CARBON'],
      ['MSI', 'X99A SLI PLUS'],
      ['MSI', 'X99S SLI PLUS'],
      ['MSI', 'X99A GODLIKE GAMING'],
      ['MSI', 'X99A WORKSTATION'],
      ['MSI', 'X99A GAMING 7'],
      ['MSI', 'X99A RAIDER'],
      ['MSI', 'X99S GAMING 7'],
      ['MSI', 'X99A XPOWER AC'],
      ['Gigabyte', 'X99-UD4'],
      ['Gigabyte', 'X99-Gaming 5'],
      ['Gigabyte', 'X99-Gaming G1 WIFI'],
      ['Gigabyte', 'X99-SOC Champion'],
      ['Gigabyte', 'X99-Designare EX'],
      ['Gigabyte', 'X99-UD3'],
      ['Gigabyte', 'X99-Ultra Gaming'],
      ['Gigabyte', 'X99P-SLI'],
      ['ASRock', 'X99 Taichi'],
      ['ASRock', 'X99 Extreme4'],
      ['ASRock', 'X99 Extreme6'],
      ['ASRock', 'X99 Professional'],
      ['ASRock', 'Fatal1ty X99 Professional'],
      ['ASRock', 'Fatal1ty X99X Killer'],
      ['ASRock', 'X99 WS'],
      ['ASRock', 'X99M Extreme4'],
      ['EVGA', 'X99 Classified'],
      ['EVGA', 'X99 FTW K'],
      ['EVGA', 'X99 Micro'],
      ['EVGA', 'X99 Micro2'],
      ['HUANANZHI', 'X99-TF'],
      ['HUANANZHI', 'X99-F8'],
      ['HUANANZHI', 'X99-T8'],
      ['HUANANZHI', 'X99-AD4'],
      ['HUANANZHI', 'X99-BD4'],
      ['HUANANZHI', 'X99-8M'],
      ['HUANANZHI', 'X99-QD4'],
      ['HUANANZHI', 'X99-P4'],
      ['HUANANZHI', 'X99-TF GAMING'],
      ['Machinist', 'X99 MR9A'],
      ['Machinist', 'X99 MR9S'],
      ['Machinist', 'X99 MR9A PRO'],
      ['Machinist', 'X99-RS9'],
      ['Machinist', 'X99-K9'],
      ['Machinist', 'X99 Z V102'],
      ['Kllisre', 'X99 ZX-DU99D4'],
      ['Kllisre', 'X99D4'],
      ['Kllisre', 'X99 D4'],
      ['Kllisre', 'X99A'],
      ['Kllisre', 'X99 ZX-DU99D3'],
      ['Kllisre', 'X99H'],
    ],
    cpus: [
      { string: 'Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz', part: 'Xeon' },
      { string: 'Intel(R) Core(TM) i7-5960X CPU @ 3.00GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz', part: 'Core i7' },
    ],
    ramSpeeds: [2133, 2400],
    dimmCounts: [2, 4],
  },

  // Z97 / H97 (LGA1150, Haswell Refresh)
  {
    boards: [
      ['ASUS', 'Z97-A'],
      ['ASUS', 'Z97-PRO'],
      ['ASUS', 'Z97-DELUXE'],
      ['ASUS', 'MAXIMUS VII HERO'],
      ['ASUS', 'Z97-K'],
      ['ASUS', 'Z97-AR'],
      ['MSI', 'Z97 GAMING 5'],
      ['MSI', 'Z97-G45 GAMING'],
      ['MSI', 'Z97 MPOWER'],
      ['MSI', 'Z97S SLI Krait Edition'],
      ['Gigabyte', 'GA-Z97X-UD5H'],
      ['Gigabyte', 'GA-Z97X-Gaming 7'],
      ['Gigabyte', 'GA-Z97X-SLI'],
      ['Gigabyte', 'GA-Z97X-SOC Force'],
      ['ASRock', 'Z97 Extreme4'],
      ['ASRock', 'Z97 Extreme6'],
      ['ASRock', 'Fatal1ty Z97 Killer'],
      ['ASRock', 'Z97 Anniversary'],
    ],
    cpus: [
      { string: 'Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz', part: 'Core i5' },
      { string: 'Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz', part: 'Xeon' },
    ],
    ramSpeeds: [1600, 1866, 2133],
    dimmCounts: [2, 4],
  },

  // Z170 / B150 (LGA1151, Skylake)
  {
    boards: [
      ['ASUS', 'Z170-A'],
      ['ASUS', 'Z170 PRO GAMING'],
      ['ASUS', 'Z170-DELUXE'],
      ['ASUS', 'MAXIMUS VIII HERO'],
      ['ASUS', 'Z170-K'],
      ['ASUS', 'Z170-AR'],
      ['MSI', 'Z170A GAMING M5'],
      ['MSI', 'Z170A KRAIT GAMING'],
      ['MSI', 'Z170A SLI PLUS'],
      ['MSI', 'Z170A GAMING PRO CARBON'],
      ['Gigabyte', 'GA-Z170X-Gaming 7'],
      ['Gigabyte', 'GA-Z170X-UD5'],
      ['Gigabyte', 'GA-Z170X-Gaming 5'],
      ['Gigabyte', 'GA-Z170-HD3'],
      ['ASRock', 'Z170 Extreme4'],
      ['ASRock', 'Fatal1ty Z170 Gaming K6'],
      ['ASRock', 'Z170 Pro4S'],
      ['ASRock', 'Z170 Extreme6'],
    ],
    cpus: [
      { string: 'Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz', part: 'Core i5' },
      { string: 'Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz', part: 'Xeon' },
    ],
    ramSpeeds: [2133, 2400],
    dimmCounts: [2, 4],
  },

  // Z270 / B250 (LGA1151, Kaby Lake)
  {
    boards: [
      ['ASUS', 'PRIME Z270-A'],
      ['ASUS', 'ROG STRIX Z270E GAMING'],
      ['ASUS', 'ROG MAXIMUS IX HERO'],
      ['ASUS', 'PRIME Z270-AR'],
      ['ASUS', 'TUF Z270 MARK 1'],
      ['MSI', 'Z270 GAMING M5'],
      ['MSI', 'Z270 GAMING PRO CARBON'],
      ['MSI', 'Z270 SLI PLUS'],
      ['MSI', 'Z270 KRAIT GAMING'],
      ['Gigabyte', 'GA-Z270X-Gaming 7'],
      ['Gigabyte', 'GA-Z270X-Ultra Gaming'],
      ['Gigabyte', 'GA-Z270X-UD5'],
      ['Gigabyte', 'GA-Z270-HD3'],
      ['ASRock', 'Z270 Extreme4'],
      ['ASRock', 'Fatal1ty Z270 Gaming K6'],
      ['ASRock', 'Z270 Taichi'],
      ['ASRock', 'Z270 Pro4'],
    ],
    cpus: [
      { string: 'Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz', part: 'Core i5' },
      { string: 'Intel(R) Xeon(R) CPU E3-1230 v6 @ 3.50GHz', part: 'Xeon' },
      { string: 'Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz', part: 'Xeon' },
    ],
    ramSpeeds: [2133, 2400, 2666],
    dimmCounts: [2, 4],
  },

  // Z370 / Z390 / B360 / B365 (LGA1151v2, Coffee Lake)
  {
    boards: [
      ['ASUS', 'ROG STRIX Z390-E GAMING'],
      ['ASUS', 'PRIME Z390-A'],
      ['ASUS', 'ROG MAXIMUS XI HERO'],
      ['ASUS', 'TUF Z390-PLUS GAMING'],
      ['ASUS', 'PRIME Z370-A'],
      ['ASUS', 'ROG STRIX Z370-E GAMING'],
      ['ASUS', 'PRIME Z370-A II'],
      ['MSI', 'Z390 GAMING EDGE AC'],
      ['MSI', 'MAG Z390 TOMAHAWK'],
      ['MSI', 'Z390-A PRO'],
      ['MSI', 'MPG Z390 GAMING PRO CARBON'],
      ['MSI', 'Z370 GAMING PLUS'],
      ['MSI', 'Z370-A PRO'],
      ['Gigabyte', 'Z390 AORUS PRO'],
      ['Gigabyte', 'Z390 AORUS MASTER'],
      ['Gigabyte', 'Z390 GAMING X'],
      ['Gigabyte', 'Z390 UD'],
      ['Gigabyte', 'Z370 AORUS Gaming 7'],
      ['Gigabyte', 'Z370 AORUS Gaming 5'],
      ['ASRock', 'Z390 Taichi'],
      ['ASRock', 'Z390 Extreme4'],
      ['ASRock', 'Z390 Phantom Gaming 6'],
      ['ASRock', 'Z370 Extreme4'],
      ['ASRock', 'Fatal1ty Z370 Gaming K6'],
    ],
    cpus: [
      { string: 'Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz', part: 'Core i9' },
      { string: 'Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz', part: 'Core i9' },
      { string: 'Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz', part: 'Core i5' },
    ],
    ramSpeeds: [2400, 2666, 3200],
    dimmCounts: [2, 4],
  },

  // Z490 / Z590 / B460 / B560 (LGA1200, Comet/Rocket Lake)
  {
    boards: [
      ['ASUS', 'ROG STRIX Z490-E GAMING'],
      ['ASUS', 'PRIME Z490-A'],
      ['ASUS', 'ROG MAXIMUS XII HERO'],
      ['ASUS', 'TUF GAMING Z490-PLUS'],
      ['ASUS', 'ROG STRIX Z590-E GAMING WIFI'],
      ['ASUS', 'PRIME Z590-A'],
      ['ASUS', 'ROG MAXIMUS XIII HERO'],
      ['ASUS', 'TUF GAMING Z590-PLUS WIFI'],
      ['MSI', 'MAG Z490 TOMAHAWK'],
      ['MSI', 'MPG Z490 GAMING EDGE WIFI'],
      ['MSI', 'Z490-A PRO'],
      ['MSI', 'MEG Z490 UNIFY'],
      ['MSI', 'MAG Z590 TOMAHAWK WIFI'],
      ['MSI', 'MPG Z590 GAMING CARBON WIFI'],
      ['MSI', 'Z590-A PRO'],
      ['Gigabyte', 'Z490 AORUS MASTER'],
      ['Gigabyte', 'Z490 AORUS PRO AX'],
      ['Gigabyte', 'Z490 GAMING X'],
      ['Gigabyte', 'Z490 UD'],
      ['Gigabyte', 'Z590 AORUS MASTER'],
      ['Gigabyte', 'Z590 AORUS PRO AX'],
      ['Gigabyte', 'Z590 GAMING X'],
      ['Gigabyte', 'Z590 UD'],
      ['ASRock', 'Z490 Taichi'],
      ['ASRock', 'Z490 Extreme4'],
      ['ASRock', 'Z490 Phantom Gaming 4'],
      ['ASRock', 'Z490 Steel Legend'],
      ['ASRock', 'Z590 Taichi'],
      ['ASRock', 'Z590 Extreme4 WiFi 6E'],
      ['ASRock', 'Z590 Steel Legend WiFi 6E'],
    ],
    cpus: [
      { string: 'Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz', part: 'Core i9' },
      { string: 'Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz', part: 'Core i9' },
      { string: 'Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i7-11700K CPU @ 3.60GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i7-11700 CPU @ 2.50GHz', part: 'Core i7' },
      { string: 'Intel(R) Core(TM) i9-11900K CPU @ 3.50GHz', part: 'Core i9' },
      { string: 'Intel(R) Core(TM) i5-11600K CPU @ 3.90GHz', part: 'Core i5' },
      { string: 'Intel(R) Core(TM) i5-11400F CPU @ 2.60GHz', part: 'Core i5' },
    ],
    ramSpeeds: [2666, 3200, 3600],
    dimmCounts: [2, 4],
  },
];
