import type { PersonData } from '../../../types';

export const countries = ['Turkey', 'Ukraine'];

const turkishFirstNames = [
  'Mehmet',
  'Ahmet',
  'Ali',
  'Mustafa',
  'Hüseyin',
  'Hasan',
  'İbrahim',
  'Osman',
  'Yusuf',
  'Murat',
  'Fatma',
  'Ayşe',
  'Emine',
  'Hatice',
  'Zeynep',
  'Elif',
  'Meryem',
  'Şerife',
  'Sultan',
  'Havva',
  'Abdulhaşim',
  'Akarsu',
  'Akdoğ',
  'Altuna',
  'Anı',
  'Argın',
  'Atfi',
  'Atl',
  'Ayişe',
  'Ayni',
  'Aysima',
  'Ayulduz',
  'Ayşekadin',
  'Bahaittin',
  'Bahti',
  'Baybek',
  'Beray',
  'Bilal',
  'Boz',
  'Cevher',
  'Dadak',
  'Dayı',
  'Demirbüken',
  'Dinçsay',
  'Duruöz',
  'Edaviye',
  'Ejder',
  'Ercihan',
  'Eroğan',
  'Esmanperi',
];

const turkishLastNames = [
  'Yılmaz',
  'Kaya',
  'Demir',
  'Şahin',
  'Çelik',
  'Yıldız',
  'Öztürk',
  'Aydın',
  'Özdemir',
  'Arslan',
  'Doğan',
  'Kılıç',
  'Aslan',
  'Çetin',
  'Kara',
  'Koç',
  'Kurt',
  'Özkan',
  'Şimşek',
  'Polat',
  'Demir',
  'Olmaz',
  'Kırış',
  'Yeşil',
  'Kaskalan',
  'Ulutaş',
  'Aydın',
  'İlker',
  'Şen',
  'Dayangaç',
  'Arslankeçecioğlu',
  'Akdemir',
  'Güzelküçük',
  'Yılmaz',
  'Şahin',
  'Bayraktaroğlu',
  'Atik',
  'Babayiğit',
  'Demirel',
  'Avlanır',
  'Gülşan',
  'Yazak',
  'Apaydın',
  'Demirtaş',
  'Filiz',
  'Dere',
  'Özcan',
  'Bozoğlu',
  'Kaan',
  'Fişekci',
];

const ukrainianFirstNames = [
  'Олександр',
  'Андрій',
  'Володимир',
  'Сергій',
  'Іван',
  'Михайло',
  'Юрій',
  'Віктор',
  'Петро',
  'Дмитро',
  'Олена',
  'Наталія',
  'Тетяна',
  'Світлана',
  'Ірина',
  'Марія',
  'Анна',
  'Людмила',
  'Галина',
  'Валентина',
  'Олег',
  'Роман',
  'Максим',
  'Артем',
  'Богдан',
  'Євген',
  'Павло',
  'Тарас',
  'Микола',
  'Григорій',
  'Катерина',
  'Юлія',
  'Оксана',
  'Любов',
  'Віра',
  'Надія',
  'Софія',
  'Аліна',
  'Дарина',
  'Вероніка',
];

const ukrainianLastNames = [
  'Шевченко',
  'Коваленко',
  'Бондаренко',
  'Ткаченко',
  'Петренко',
  'Олійник',
  'Кравченко',
  'Шевчук',
  'Гаврилюк',
  'Поліщук',
  'Ковальчук',
  'Кузьменко',
  'Марченко',
  'Литвиненко',
  'Іванов',
  'Сидоренко',
  'Мельник',
  'Бойко',
  'Коваленко',
  'Мороз',
  'Руденко',
  'Савченко',
  'Павленко',
  'Захарченко',
  'Харченко',
  'Макаренко',
  'Федоренко',
  'Ткачук',
  'Гнатюк',
  'Данилюк',
  'Лисенко',
  'Романюк',
  'Костенко',
  'Михайленко',
  'Василенко',
  'Пономаренко',
  'Гриценко',
  'Яценко',
  'Дяченко',
  'Тимошенко',
];

const turkeyAddresses = [
  {
    street: 'Uludağ Caddesi',
    houseNumber: '250',
    locality: 'Yiğitali',
    region: 'Osmangazi̇',
    province: 'Bursa',
    postalCode: '16370',
  },
  {
    street: 'Özgül Sok',
    houseNumber: '3',
    locality: 'Ömeranlı',
    region: 'Kulu',
    province: 'Konya',
    postalCode: '42770',
  },
  {
    street: 'Derviş Görgün Caddesi',
    houseNumber: '43',
    locality: 'Umurça',
    region: 'Bodrum',
    province: 'Muğla',
    postalCode: '48470',
  },
  {
    street: 'Ömer Akpınar Caddesi',
    houseNumber: '39',
    locality: 'Alipaşa',
    region: 'Akpınar',
    province: 'Kırşehir',
    postalCode: '40320',
  },
  {
    street: 'Esat Caddesi',
    houseNumber: '143',
    locality: 'Küçükesat',
    region: 'Çankaya',
    province: 'Ankara',
    postalCode: '06660',
  },
  {
    street: 'Şehit Cengiz Topel Caddesi',
    houseNumber: '36',
    locality: 'Bostanlı',
    region: 'Karşıyaka',
    province: 'İzmir',
    postalCode: '35590',
  },
  {
    street: 'İsmet Paşa Caddesi',
    houseNumber: '38',
    locality: 'Çay',
    region: 'Gökçebey',
    province: 'Zonguldak',
    postalCode: '67670',
  },
  {
    street: 'Atatürk Caddesi',
    houseNumber: '25',
    locality: 'Yusufpaşa',
    region: 'Kars Merkez',
    province: 'Kars',
    postalCode: '36100',
  },
  {
    street: 'Kurtalan Yolu Caddesi',
    houseNumber: '132',
    locality: 'Kooperatif',
    region: 'Siirt Merkez',
    province: 'Siirt',
    postalCode: '56100',
  },
  {
    street: 'İnönü Caddesi',
    houseNumber: '97',
    locality: 'Gülabibey',
    region: 'Çorum Merkez',
    province: 'Çorum',
    postalCode: '19100',
  },
];

const ukraineAddresses = [
  {
    street: 'вул. Хрещатик',
    houseNumber: '15',
    locality: 'Київ',
    region: 'Київська',
    province: 'Київ',
    postalCode: '01001',
  },
  {
    street: 'вул. Дерибасівська',
    houseNumber: '8',
    locality: 'Одеса',
    region: 'Одеська',
    province: 'Одеса',
    postalCode: '65026',
  },
  {
    street: 'просп. Свободи',
    houseNumber: '25',
    locality: 'Львів',
    region: 'Львівська',
    province: 'Львів',
    postalCode: '79000',
  },
  {
    street: 'вул. Сумська',
    houseNumber: '35',
    locality: 'Харків',
    region: 'Харківська',
    province: 'Харків',
    postalCode: '61000',
  },
  {
    street: 'вул. Центральна',
    houseNumber: '42',
    locality: 'Дніпро',
    region: 'Дніпропетровська',
    province: 'Дніпро',
    postalCode: '49000',
  },
  {
    street: 'вул. Головна',
    houseNumber: '12',
    locality: 'Вінниця',
    region: 'Вінницька',
    province: 'Вінниця',
    postalCode: '21000',
  },
  {
    street: 'просп. Миру',
    houseNumber: '78',
    locality: 'Запоріжжя',
    region: 'Запорізька',
    province: 'Запоріжжя',
    postalCode: '69000',
  },
  {
    street: 'вул. Незалежності',
    houseNumber: '5',
    locality: 'Івано-Франківськ',
    region: 'Івано-Франківська',
    province: 'Івано-Франківськ',
    postalCode: '76000',
  },
  {
    street: 'вул. Шевченка',
    houseNumber: '22',
    locality: 'Тернопіль',
    region: 'Тернопільська',
    province: 'Тернопіль',
    postalCode: '46000',
  },
  {
    street: 'вул. Грушевського',
    houseNumber: '18',
    locality: 'Ужгород',
    region: 'Закарпатська',
    province: 'Ужгород',
    postalCode: '88000',
  },
];

const generateRandomBirthDate = (): string => {
  const startDate = new Date(1970, 0, 1);
  const endDate = new Date(2000, 11, 31);
  const randomDate = new Date(
    startDate.getTime() + Math.random() * (endDate.getTime() - startDate.getTime()),
  );

  const day = String(randomDate.getDate()).padStart(2, '0');
  const month = String(randomDate.getMonth() + 1).padStart(2, '0');
  const year = randomDate.getFullYear();

  return `${day}-${month}-${year}`;
};

export const generateRandomPersonData = (country: string): PersonData => {
  let firstName: string;
  let lastName: string;
  let address: (typeof turkeyAddresses)[0];

  if (country === 'Turkey') {
    firstName = turkishFirstNames[Math.floor(Math.random() * turkishFirstNames.length)];
    lastName = turkishLastNames[Math.floor(Math.random() * turkishLastNames.length)];
    address = turkeyAddresses[Math.floor(Math.random() * turkeyAddresses.length)];
  } else {
    firstName = ukrainianFirstNames[Math.floor(Math.random() * ukrainianFirstNames.length)];
    lastName = ukrainianLastNames[Math.floor(Math.random() * ukrainianLastNames.length)];
    address = ukraineAddresses[Math.floor(Math.random() * ukraineAddresses.length)];
  }

  return {
    first_name: firstName,
    last_name: lastName,
    birth_date: generateRandomBirthDate(),
    country,
    city: address.locality,
    address: `${address.street} ${address.houseNumber}`,
    zip: address.postalCode,
  };
};
